[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[colors.primary]
background = '0x000000'
foreground = '0x00FF00'

[colors.cursor]
text = '0x000000'
cursor = '0x00FF00'

[colors.selection]
text = '0x000000'
background = '0x00FF00'

[colors.normal]
black   = "0x0A0A0A"
red     = "0xFF3C3C"
green   = "0x00FF00"
yellow  = "0xE5C07B"
blue    = "0x0087FF"
magenta = "0xFF00FF"
cyan    = "0x00FFFF"
white   = "0xBFBFBF"

[colors.bright]
black   = "0x1A1A1A"
red     = "0xFF6B6B"
green   = "0x33FF33"
yellow  = "0xFFFF88"
blue    = "0x3399FF"
magenta = "0xFF77FF"
cyan    = "0x77FFFF"
white   = "0xFFFFFF"
